export const defaultContent: Record<string, string> = {
  heading: 'Pizza Palace',
  subheading: 'Authentic wood-fired pizzas since 1998',
  phone: '+91 98765 43210',
  address: '123 Main Street, Mumbai',
  hours: 'Open daily: 11 AM - 11 PM',
  item_1_name: 'Margherita',
  item_1_desc: 'Classic tomato sauce, fresh mozzarella, and basil',
  item_1_price: '299',
  item_1_emoji: '🧀',
  item_2_name: 'BBQ Chicken',
  item_2_desc: 'Smoky BBQ sauce, grilled chicken, onions, and cilantro',
  item_2_price: '399',
  item_2_emoji: '🍗',
  item_3_name: 'Pepperoni',
  item_3_desc: 'Spicy pepperoni, mozzarella, and tomato sauce',
  item_3_price: '349',
  item_3_emoji: '🌶️',
  item_4_name: 'Veggie Supreme',
  item_4_desc: 'Bell peppers, mushrooms, olives, onions, and tomatoes',
  item_4_price: '329',
  item_4_emoji: '🥗',
  item_5_name: 'Hawaiian',
  item_5_desc: 'Ham, pineapple, and mozzarella (yes, we dare!)',
  item_5_price: '369',
  item_5_emoji: '🍍',
  item_6_name: 'Paneer Tikka',
  item_6_desc: 'Tandoori paneer, onions, capsicum, and mint chutney',
  item_6_price: '379',
  item_6_emoji: '🧈',
};
